name: do_sherlock
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - blas[build=mkl]
  - scipy
  - cvxpy
  - scikit-learn
  - pandas
  - google-auth
  - pandas-gbq>=0.19.2
  - dask
  - dask-jobqueue
  - coiled
  - sqlalchemy
  - pg8000
  - cloud-sql-python-connector
  - pip
  - pip:
    - git+https://github.com/adonoho/EMS.git
variables:
  MKL_NUM_THREADS: '1'
  OPENBLAS_NUM_THREADS: '1'
